# Generated by Django 3.2.7 on 2023-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airtime',
            old_name='agent_rate',
            new_name='diamond_rate',
        ),
        migrations.RenameField(
            model_name='airtime',
            old_name='user_rate',
            new_name='gold_rate',
        ),
        migrations.RenameField(
            model_name='cableplan',
            old_name='agent_price',
            new_name='diamond_price',
        ),
        migrations.RenameField(
            model_name='cableplan',
            old_name='user_price',
            new_name='gold_price',
        ),
        migrations.RenameField(
            model_name='dataplan',
            old_name='agent_price',
            new_name='diamond_price',
        ),
        migrations.RenameField(
            model_name='dataplan',
            old_name='user_price',
            new_name='gold_price',
        ),
        migrations.RenameField(
            model_name='disco',
            old_name='agent_convinience_fee',
            new_name='diamond_convinience_fee',
        ),
        migrations.RenameField(
            model_name='disco',
            old_name='user_convinience_fee',
            new_name='gold_convinience_fee',
        ),
        migrations.AddField(
            model_name='airtime',
            name='silver_rate',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='cableplan',
            name='silver_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataplan',
            name='silver_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disco',
            name='silver_convinience_fee',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
